
class DAOObject{

    private Double x1;
    private Double x2;

    //getter and setters and constructors are autogenerated

    public DAOObject(Double x1, Double x2) {
        this.x1 = x1;
        this.x2 = x2;
    }

    public DAOObject() {
    }

    public Double getX1() {
        return x1;
    }

    public void setX1(Double x1) {
        this.x1 = x1;
    }

    public Double getX2() {
        return x2;
    }

    public void setX2(Double x2) {
        this.x2 = x2;
    }

    //autogenerated
    @Override
    public boolean equals(Object o) {

        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        DAOObject daoObject = (DAOObject) o;

        if (getX1() != null ? !getX1().equals(daoObject.getX1()) : daoObject.getX1() != null) return false;
        return !(getX2() != null ? !getX2().equals(daoObject.getX2()) : daoObject.getX2() != null);

    }


    //autogenerated
    @Override
    public int hashCode() {
        int result = getX1() != null ? getX1().hashCode() : 0;
        result = 31 * result + (getX2() != null ? getX2().hashCode() : 0);
        return result;
    }


    //autogenerated
    @Override
    public String toString() {
        return "DAOObject{" +
                "x1=" + x1 +
                ", x2=" + x2 +
                '}';
    }
}
